if (!(Test-Path -Path C:\temp )) { New-Item -ItemType directory -Path C:\temp };secedit /export /cfg C:\temp\secpol.cfg;
Write-Output '====';
[System.Net.Dns]::GetHostName();
;Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows Nt\Currentversion' -Name 'CurrentBuild';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'AllowBehaviorMonitoring';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'PUAProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'AllowEmailScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'AllowFullScanRemovableDriveScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'AllowRealtimeMonitoring';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'AllowIOAVProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'AllowScriptScanning';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'ASRRules';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Policy Manager' -Name 'EnableNetworkProtection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DeviceGuard' -Name 'EnableVirtualizationBasedSecurity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DeviceGuard' -Name 'ConfigureSystemGuardLaunch';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DeviceGuard' -Name 'RequirePlatformSecurityFeatures';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DeviceGuard' -Name 'LsaCfgFlags';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\CloudContent' -Name 'DisableConsumerAccountStateContent';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Policies\EarlyLaunch' -Name 'DriverLoadPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}' -Name 'NoBackgroundPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{35378EAC-683F-11D2-A89A-00C04FBBCFA2}' -Name 'NoGPOListChanges';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{827D319E-6EAC-11D2-A4EA-00C04F79F83A}' -Name 'NoBackgroundPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Group Policy\{827D319E-6EAC-11D2-A4EA-00C04F79F83A}' -Name 'NoGPOListChanges';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnableCdp';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'DisableWebPnPDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoWebServices';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'BlockUserFromShowingAccountDetailsOnSignin';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DontDisplayNetworkSelectionUI';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DontEnumerateConnectedUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnumerateLocalUsers';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'DisableLockScreenAppNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'BlockDomainPicturePassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'AllowDomainPINLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\f15576e8-98b7-4186-b944-eafa664402d9' -Name 'DCSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\f15576e8-98b7-4186-b944-eafa664402d9' -Name 'ACSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51' -Name 'DCSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Power\PowerSettings\0e796bdb-100d-47d6-a2d5-f7d2daa51f51' -Name 'ACSettingIndex';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\policies\Microsoft\Windows NT\Terminal Services' -Name 'fAllowUnsolicited';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\policies\Microsoft\Windows NT\Terminal Services' -Name 'fAllowToGetHelp';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Rpc' -Name 'EnableAuthEpResolution';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Rpc' -Name 'RestrictRemoteClients';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\Audit' -Name 'ProcessCreationIncludeCmdLine_Enabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\W32Time\TimeProviders\NtpClient' -Name 'Enabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\W32Time\TimeProviders\NtpServer' -Name 'Enabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System\CredSSP\Parameters' -Name 'AllowEncryptionOracle';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\CredentialsDelegation' -Name 'AllowProtectedCreds';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Device Metadata' -Name 'PreventDeviceMetadataFromNetwork';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Setup' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\Setup' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\System' -Name 'Retention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\EventLog\System' -Name 'MaxSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'EnableSmartScreen';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoDataExecutionPrevention';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoHeapTerminationOnCorruption';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'PreXPSP2ShellProtocolBehavior';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\HomeGroup' -Name 'DisableHomeGroup';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\MicrosoftAccount' -Name 'DisableUserAuth';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender' -Name 'DisableAntiSpyware';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender\Spynet' -Name 'LocalSettingOverrideSpynetReporting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'MSAOptional';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoInplaceSharing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'DisablePasswordSaving';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'DeleteTempDirsOnExit';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fDisableCdm';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fPromptForPassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'fEncryptRPCTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'SecurityLayer';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'UserAuthentication';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Terminal Services' -Name 'MinEncryptionLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Internet Explorer\Feeds' -Name 'DisableEnclosureDownload';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsStore' -Name 'DisableOSUpgrade';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableAutomaticRestartSignOn';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments' -Name 'SaveZoneInformation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Microsoft\Windows\CurrentVersion\Policies\Attachments' -Name 'ScanWithAntiVirus';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Powershell\ScriptBlockLogging' -Name 'EnableScriptBlockLogging';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\PowerShell\Transcription' -Name 'EnableTranscripting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowBasic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowUnencryptedTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Client' -Name 'AllowDigest';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowBasic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\WinRM\Service' -Name 'AllowUnencryptedTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WinRM\Service' -Name 'DisableRunAs';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Explorer' -Name 'NoAutoplayfornonVolume';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoAutorun';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer' -Name 'NoDriveTypeAutoRun';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\CredUI' -Name 'DisablePasswordReveal';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\CredUI' -Name 'EnumerateAdministrators';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\System' -Name 'NoLocalPasswordResetQuestions';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Control Panel\Desktop' -Name 'ScreenSaveActive';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenCamera';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Personalization' -Name 'NoLockScreenSlideshow';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LocalAccountTokenFilterPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\mrxsmb10' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Services\LanmanServer\Parameters' -Name 'SMB1';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\kernel' -Name 'DisableExceptionChainValidation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\SecurityProviders\WDigest' -Name 'UseLogonCredential';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'AutoAdminLogon';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScreenSaverGracePeriod';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Eventlog\Security' -Name 'WarningLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile' -Name 'AllowLocalIPsecPolicyMerge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile' -Name 'AllowLocalPolicyMerge';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Tcpip6\Parameters' -Name 'DisableIPSourceRouting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\PublicProfile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters' -Name 'DisableIPSourceRouting';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile' -Name 'DisableNotifications';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile\Logging' -Name 'LogDroppedPackets';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Tcpip\Parameters' -Name 'EnableICMPRedirect';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile\Logging' -Name 'LogSuccessfulConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile\Logging' -Name 'LogFilePath';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\NetBT\Parameters' -Name 'NoNameReleaseOnDemand';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\DomainProfile\Logging' -Name 'LogFileSize';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile' -Name 'EnableFirewall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Session Manager' -Name 'SafeDllSearchMode';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess\Parameters\FirewallPolicy\Mdm\StandardProfile' -Name 'DefaultInboundAction';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\SYSVOL';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\NetworkProvider\HardenedPaths' -Name '\\*\NETLOGON';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy' -Name 'fMinimizeConnections';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WcmSvc\GroupPolicy' -Name 'fBlockNonDomain';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient' -Name 'EnableMulticast';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_AllowNetBridge_NLA';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_ShowSharedAccessUI';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Network Connections' -Name 'NC_StdDomainUserSetLocation';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers' -Name 'RegisterSpoolerRemoteRpcEndPoint';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'NoWarningNoElevationOnInstall';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows NT\Printers\PointAndPrint' -Name 'UpdatePromptSettings';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\CurrentVersion\PushNotifications' -Name 'NoToastApplicationNotificationOnLockScreen';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\Windows\LanmanWorkstation' -Name 'AllowInsecureGuestAuth';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'NoConnectedUser';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'ScRemoveOption';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'RequireSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnableSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanmanWorkstation\Parameters' -Name 'EnablePlainTextPassword';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RequireSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'EnableSecuritySignature';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymousSAM';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'RestrictAnonymous';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LanManServer\Parameters' -Name 'RestrictNullSessAccess';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SYSTEM\CurrentControlSet\Control\Lsa' -Name 'restrictremotesam';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'UseMachineId';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\pku2u' -Name 'AllowOnlineID';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'NoLMHash';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LMCompatibilityLevel';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinClientSec';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'NTLMMinServerSec';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa\MSV1_0' -Name 'AuditReceivingNTLMTraffic';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorAdmin';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Control\Lsa' -Name 'LimitBlankPasswordUse';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'ConsentPromptBehaviorUser';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableInstallerDetection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableSecureUIAPaths';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'FilterAdministratorToken';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'PromptOnSecureDesktop';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableLUA';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'EnableVirtualization';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DontDisplayLastUserName';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableCAD';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'InactivityTimeoutSecs';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'EnableUserControl';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKU:\Software\Policies\Microsoft\Windows\Installer' -Name 'AlwaysInstallElevated';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\WindowsStore' -Name 'RequirePrivateStoreOnly';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\SOFTWARE\Policies\Microsoft\InputPersonalization' -Name 'AllowInputPersonalization';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'NotifyMalicious';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'NotifyPasswordReuse';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'NotifyUnsafeApp';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\WTDS\Components' -Name 'ServiceEnabled';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection' -Name 'AllowTelemetry_PolicyManager';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection' -Name 'EnableOneSettingsAuditing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection' -Name 'LimitDiagnosticLogCollection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DataCollection' -Name 'LimitDumpCollection';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\LxssManager' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\FTPSVC' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\sshd' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\RpcLocator' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\RemoteAccess' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\simptcp' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\Browser' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\sacsvr' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SSDPSRV' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\upnphost' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\WMSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\WMPNetworkSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\icssvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\W3SVC' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\XboxGipSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\XblAuthManager' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\XblGameSave' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\XboxNetApiSvc' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\IISADMIN' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\irmon' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\System\CurrentControlSet\Services\SharedAccess' -Name 'Start';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows\DeviceGuard' -Name 'HypervisorEnforcedCodeIntegrity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Dsh' -Name 'AllowNewsAndInterests';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Policies\Microsoft\Windows Defender Security Center\App and Browser protection' -Name 'DisallowExploitProtectionOverride';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\PassportForWork\Biometrics' -Name 'FacialFeaturesUseEnhancedAntiSpoofing';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\WindowsInkWorkspace' -Name 'AllowWindowsInkWorkspace';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\Update' -Name 'AllowAutoUpdate';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\Update' -Name 'DeferFeatureUpdatesPeriodInDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\Update' -Name 'DeferQualityUpdatesPeriodInDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\Update' -Name 'ManagePreviewBuilds';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\Update' -Name 'ScheduledInstallDay';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\PolicyManager\Current\Device\Update' -Name 'SetDisablePauseUXAccess';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\LAPS' -Name 'BackupDirectory';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\LAPS' -Name 'PasswordAgeDays';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\LAPS' -Name 'PasswordComplexity';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\LAPS' -Name 'PasswordLength';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\LAPS' -Name 'PostAuthenticationActions';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Policies\LAPS' -Name 'PostAuthenticationResetDelay';;Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTrustedCredManAccessPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateSymbolicLinkPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateTokenPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDebugPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyNetworkLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeDenyRemoteInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeEnableDelegationPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeAuditPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeImpersonatePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeIncreaseBasePriorityPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeNetworkLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeLoadDriverPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeLockMemoryPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSecurityPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeManageVolumePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemEnvironmentPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeReLabelPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeProfileSingleProcessPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRemoteShutdownPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeRestorePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTakeOwnershipPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeTcbPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeInteractiveLogonRight';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeBackupPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeSystemTimePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreateGlobalPrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreatePagefilePrivilege';
Write-Output '====';
Get-Content -Path C:\temp\secpol.cfg | Select-String -Pattern 'SeCreatePermanentPrivilege';Write-Output '====';
net user guest | select-string -pattern 'Account active';
Write-Output '===='
net user administrator | select-string -pattern 'User name';
Write-Output '====';
net user guest | select-string -pattern 'User name';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LegalNoticeText';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'LegalNoticeCaption';;Write-Output '====';
auditpol /get /subcategory:'Credential Validation' | select-string -pattern 'Credential Validation';
Write-Output '====';
auditpol /get /subcategory:'File Share' | select-string -pattern 'File Share';
Write-Output '====';
auditpol /get /subcategory:'Other Logon/Logoff Events' | select-string -pattern 'Other Logon/Logoff Events';
Write-Output '====';
auditpol /get /subcategory:'Security Group Management' | select-string -pattern 'Security Group Management';
Write-Output '====';
auditpol /get /subcategory:'Security System Extension' | select-string -pattern 'Security System Extension';
Write-Output '====';
auditpol /get /subcategory:'Special Logon' | select-string -pattern 'Special Logon';
Write-Output '====';
auditpol /get /subcategory:'User Account Management' | select-string -pattern 'User Account Management';
Write-Output '====';
auditpol /get /subcategory:'Plug and Play Events' | select-string -pattern 'Plug and Play Events';
Write-Output '====';
auditpol /get /subcategory:'Process Creation' | select-string -pattern 'Process Creation';
Write-Output '====';
auditpol /get /subcategory:'Detailed File Share' | select-string -pattern 'Detailed File Share';
Write-Output '====';
auditpol /get /subcategory:'Other Object Access Events' | select-string -pattern 'Other Object Access Events';
Write-Output '====';
auditpol /get /subcategory:'Account Lockout' | select-string -pattern 'Account Lockout';
Write-Output '====';
auditpol /get /subcategory:'Removable Storage' | select-string -pattern 'Removable Storage';
Write-Output '====';
auditpol /get /subcategory:'MPSSVC Rule-Level Policy Change' | select-string -pattern 'MPSSVC Rule-Level Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Other Policy Change Events' | select-string -pattern 'Other Policy Change Events';
Write-Output '====';
auditpol /get /subcategory:'Sensitive Privilege Use' | select-string -pattern 'Sensitive Privilege Use';
Write-Output '====';
auditpol /get /subcategory:'IPsec Driver' | select-string -pattern 'IPsec Driver';
Write-Output '====';
auditpol /get /subcategory:'Other System Events' | select-string -pattern 'Other System Events';
Write-Output '====';
auditpol /get /subcategory:'Security State Change' | select-string -pattern 'Security State Change';
Write-Output '====';
auditpol /get /subcategory:'System Integrity' | select-string -pattern 'System Integrity';
Write-Output '====';
auditpol /get /subcategory:'Group Membership' | select-string -pattern 'Group Membership';
Write-Output '====';
auditpol /get /subcategory:'Logoff' | select-string -pattern 'Logoff';
Write-Output '====';
auditpol /get /subcategory:'Logon' | select-string -pattern 'Logon';
Write-Output '====';
auditpol /get /subcategory:'Application Group Management' | select-string -pattern 'Application Group Management';
Write-Output '====';
auditpol /get /subcategory:'Authentication Policy Change' | select-string -pattern 'Authentication Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Authorization Policy Change' | select-string -pattern 'Authorization Policy Change';
Write-Output '====';
auditpol /get /subcategory:'Audit Policy Change' | select-string -pattern 'Audit Policy Change';Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Provisioning\OMADM\Logger' -Name 'CurrentEnrollmentId';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System' -Name 'DisableBkGndGroupPolicy';
Write-Output '====';
Get-ItemPropertyValue -Path 'HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Winlogon' -Name 'DefaultPassword';;